include(cmake/include/AnimusUtilities.cmake)
include(cmake/include/AnimusDjinni.cmake)
include(cmake/include/AnimusJava.cmake)
include(cmake/include/AnimusObjc.cmake)
include(cmake/include/AnimusCPack.cmake)

animus_bootstrap()
animus_git_initialization()
animus_build_dependencies()
animus_setup_djinni_command()
animus_get_djinni_output_files()
animus_generate_objc_umbrella_header()
animus_add_djinni_targets()
animus_add_subdirectories()
animus_add_jni()
animus_add_objc()
animus_cpack()
animus_build_message()
